version: "3"
services:
  app-react:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
